import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from 'react'
import { useState } from 'react'

export const Button = ({ className = '', variant = 'primary', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger' }) => <button className={`button button--${variant} ${className}`} {...props} />
export const IconButton = ({ label, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) => <button className="icon-button" aria-label={label} title={label} {...props} />
export const Input = ({ label, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) => <label className="field"><span>{label}</span><input {...props} />{error && <small className="field__error">{error}</small>}</label>
export const PasswordInput = ({ label = 'Password', ...props }: InputHTMLAttributes<HTMLInputElement> & { label?: string }) => { const [shown, setShown] = useState(false); return <label className="field"><span>{label}</span><div className="password-field"><input type={shown ? 'text' : 'password'} {...props}/><button type="button" onClick={() => setShown(!shown)} aria-label={shown ? 'Hide password' : 'Show password'}>{shown ? 'Hide' : 'Show'}</button></div></label> }
export const Checkbox = ({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: ReactNode }) => <label className="checkbox"><input type="checkbox" {...props}/><span>{label}</span></label>
export const Select = ({ label, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string }) => <label className="field"><span>{label}</span><select {...props}>{children}</select></label>
export const Badge = ({ children, tone = 'blue' }: { children: ReactNode; tone?: 'blue' | 'purple' | 'green' | 'amber' | 'red' | 'neutral' }) => <span className={`badge badge--${tone}`}>{children}</span>
export const StatusPill = Badge
export const Card = ({ children, className = '', glow = false }: { children: ReactNode; className?: string; glow?: boolean }) => <section className={`card ${glow ? 'card--glow' : ''} ${className}`}>{children}</section>
export const MetricCard = ({ label, value, detail, tone = 'blue' }: { label: string; value: string | number; detail?: string; tone?: 'blue' | 'green' | 'purple' | 'amber' }) => <Card className={`metric-card metric-card--${tone}`}><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</Card>
export const ProgressIndicator = ({ step, total = 4 }: { step: number; total?: number }) => <div className="progress" aria-label={`Step ${step} of ${total}`}>{Array.from({ length: total }, (_, i) => <div key={i} className={i + 1 <= step ? 'is-complete' : ''}><i/>{i + 1 === step && <span>Step {step} of {total}</span>}</div>)}</div>
export const Tabs = ({ tabs, active, onChange }: { tabs: string[]; active: string; onChange: (tab: string) => void }) => <div className="tabs" role="tablist">{tabs.map((tab) => <button type="button" role="tab" aria-selected={active === tab} className={active === tab ? 'is-active' : ''} onClick={() => onChange(tab)} key={tab}>{tab}</button>)}</div>
export const SectionHeader = ({ title, eyebrow, action }: { title: string; eyebrow?: string; action?: ReactNode }) => <header className="section-header"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action}</header>
export const Divider = () => <hr className="divider"/>
export const Alert = ({ children, tone = 'info' }: { children: ReactNode; tone?: 'info' | 'success' | 'warning' | 'critical' }) => <div role="status" className={`alert alert--${tone}`}>{children}</div>
export const EmptyState = ({ title = 'Nothing to show', message = 'Data will appear here when it becomes available.' }: { title?: string; message?: string }) => <Card className="state"><strong>{title}</strong><p>{message}</p></Card>
export const LockedState = ({ message = 'Verify your account to unlock protected intelligence.' }: { message?: string }) => <Card className="state"><span className="state__icon">◇</span><strong>Workspace locked</strong><p>{message}</p><Button>Verify account</Button></Card>
export const LoadingState = () => <div className="loading" role="status"><i/><span>Loading intelligence…</span></div>
export const ModalShell = ({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) => open ? <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><div className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(e) => e.stopPropagation()}><SectionHeader title={title} action={<IconButton label="Close" onClick={onClose}>×</IconButton>}/>{children}</div></div> : null
export const Toast = ({ message }: { message: string }) => <div className="toast" role="status">{message}</div>
